### ISSUE TITLE
Cleaning

### ISSUE THREAD

**Issue by moteus** [stevedonovan/Lake#10]
1. clean target for msvc does not delete *.lib and *.exp files.
2. It would be convenient if we can add own actions to clean target.

``` lua
mytarget = target(...)
mytarget:clean(action(...),action(...))
```

**Comment by stevedonovan** [comment]
Good points. I'll update to clear the .lib and .exp files, and extending the clean target is a useful idea.

**Comment by moteus** [comment]
Also *.pdb file
