### ISSUE TITLE
recurcive file.group

### ISSUE THREAD

**Issue by moteus** [stevedonovan/Lake#11]
recurcive copy does not create directory tree

``` lua
  file.group{odir=J(INSTALL_DIR, 'test' ); recurse=true; src = J('test', '*.*') };
```

produce:
  copy test\ex\test.lua lib\test\test.lua > nul
  copy test\luasql\odbc.lua lib\test\odbc.lua > nul
  copy test\testdb.sql lib\test\testdb.sql > nul

**Comment by stevedonovan** [comment]
Yes, good point. The recurse option was originally for selecting source files, but I will see if we can make file.group behave in the way you want.

**Comment by andrewstarks** [comment]
++ on this one. Having a way to map/copy a tree would be excellent, ala xcopy.

**Comment by stevedonovan** [comment]
OK, let's do it, in a platform-aware way.  (For Windows xcopy does fine, `cp -r` works fine on Linux, not sure about OS X)

**Comment by stevedonovan** [comment]
Looks like its `cp -R` 

https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/cp.1.html

If you compare this BSD cp to the Linux cp you'll see they're rather different beasts!

**Comment by moteus** [comment]
It is already work. Should we close this issuse

**Comment by stevedonovan** [comment]
Alexey, I had forgotten that I'd fixed this issue ;)  `file.group` should be the way to do it, although perhaps I'll provide a `file.copy_tree` to do wholesale copies directly.

**Comment by moteus** [comment]
Copy files without extension still do not work :(
Do i need open new issuae?
