### ISSUE TITLE
.def file and base option

### ISSUE THREAD

**Issue by moteus** [stevedonovan/Lake#12]
In root dir i have 

```
src\mylib.c
src\mylib.def
lakefile
```

lakefile:

``` Lua
c.shared{'mylib', base = 'src', need='lua'}
```

Lake do not found .def file.

**Comment by stevedonovan** [comment]
Yes, definitely a problem.  I will have a new version out in next week, but I will fix this one today.

**Comment by moteus** [comment]
Thx. But I can wait.
