### ISSUE TITLE
DEF switch for lib.exe (MSVC)

### ISSUE THREAD

**Issue by moteus** [stevedonovan/Lake#22]
This switch use to create no static lib file from binary (.dll)

**Comment by stevedonovan** [comment]
You will have to give more details, please.  We do use /DEF with lib.exe when Lake finds a .def file to create a dynamic lib file AFAIK ;)

**Comment by moteus** [comment]
cl /nologo -c /O1 /WX /DWINDOWS /D_WINDLL /D_USRDLL /DNDEBUG /DSQLITE_ENABLE_RTREE /DSQLITE_ENABLE_COLUMN_METADATA 
 /MT /D_CRT_SECURE_NO_DEPRECATE /DNDEBUG /showIncludes  .\sqlite3.c /Fo.\sqlite3.obj
link /nologo .\sqlite3.obj /DEF:.\sqlite3.def  /DLL /OUT:.\sqlite3.dll
lib /nologo .\sqlite3.obj /DEF:.\sqlite3.def /OUT:.\sqlite3_static.lib

sqlite3_static.lib is not static library, but import library createt based on sqlite3.obj (its the same as sqlite3.lib)
if remove /DEF
lib /nologo .\sqlite3.obj  /OUT:.\sqlite3_static.lib
we get real static library.

http://msdn.microsoft.com/en-us/library/0b9xe492.aspx

**Comment by stevedonovan** [comment]
ah, thank you.  That is a definite issue to be sorted out.  I want to do a new Lake release in the next few weeks.

**Comment by moteus** [comment]
Sorry for askind here, but ehether it is worth expecting in the future release function needs (#21)?

**Comment by stevedonovan** [comment]
I think that is a good generalization, looking at your example.  Definitely should be straightforward (Lua is great in that way)

**Comment by stevedonovan** [comment]
I think this has been sorted - I am now only doing this for DLLs!
