### ISSUE TITLE
Source file with space breaks `lake <source>` usage

### ISSUE THREAD

**Issue by cehoffman** [stevedonovan/Lake#23]
I tried compiling a source file using the shorthand of calling lake with the file and it broke on the space.

```
$ lake "Terminal Hotkey.c"
lake: cannot find dependency 'Terminal.c'
```

**Comment by stevedonovan** [comment]
Ouch!  Lake is being far too eager to break space-delimited strings into lists...  I'll special-case this, and see what other problems we have with files-with-spaces.

**Comment by stevedonovan** [comment]
It's a minefield. So I'm closing this one as a WONTFIX.
