### ISSUE TITLE
Using LUA_INCLUDE_DIR insted of LUA_INCLUDE

### ISSUE THREAD

**Issue by moteus** [stevedonovan/Lake#28]
After i try build my project i got

```
lake: cannot find Lua include files
Specify LUA_INCLUDE
```

But in real i need set LUA_INCLUDE_DIR variable

``` bash
lake LUA_INCLUDE_DIR=...
```

**Comment by stevedonovan** [comment]
Thanks for the report. I'm getting Lake ready for a release, so it's time to hit any remaining issues hard.
