### ISSUE TITLE
file.group on *nix

### ISSUE THREAD

**Issue by moteus** [stevedonovan/Lake#31]
[lua-AesFileEncrypt](https://github.com/moteus/lua-AesFileEncrypt/tree/5a3812d3f8c90cf78b861f08bdbc61a0d7402643)
On Windows/MinGW build ok.
On [BuildHive](https://buildhive.cloudbees.com/job/moteus/job/lua-AesFileEncrypt/59/console) i get

``` bash
$ LAKE LUA_RUNNER=LUA LUA_INCLUDE_DIR=$LUA_INCLUDE ROOT=$LUA_SHARE/AesFileEncrypt LUADIR=$LUA_LIBS LIBDIR=$LUA_LIBS clean install test
.....
cp: cannot stat `src/fileenc/test*': No such file or directory
......
cp src/fileenc/test* /scratch/jenkins/workspace/moteus/lua-AesFileEncrypt/lua51/share/AesFileEncrypt/test/test*
```

**Comment by stevedonovan** [comment]
I've just tried the following little lakefile on LInux:

``` lua
default{file.group{src='dir/one*',odir='out'}}
```

where `dir` contains `one.c` and `oneone.c`.

Seems to work fine here:

```
cp dir/one.c out/one.c
cp dir/oneone.c out/oneone.c
```

Saying it cannot stat 'src/fileenc/test*' means that it has not expanded that wildcard?

**Comment by moteus** [comment]
This does not work

``` Lua
install = target('install', {
  file.group{odir=LIBDIR; src = AesFileEncrypt };
  file.group{odir=J(ROOT, 'test'); src = AesFileEncryptTest };
  file.group{odir=J(ROOT, 'test'); src = J('test', '*.*') };
})
```

This works

``` Lua
install = target('install', {
  file.group{odir=LIBDIR; src = AesFileEncrypt };
  file.group{odir=J(ROOT, 'test'); src = J('test', '*.*') };
})
```

Problem appear when i add build and install `AesFileEncryptTest` to lakefile.
Now master has worked lakefile. But reference from my post point on non working.
`lua-AesFileEncrypt` has no external deps so you can try build.
this command should work

``` bash
# ROOT/test Where install tests
# LIBDIR    Where install c lib
# LUADIR    Where install lua lib
lake ROOT=$TEMP/AesFileEncrypt LIBDIR=$TEMP/AesFileEncrypt  install
```

**Comment by moteus** [comment]
I think i can reproduce this:
FS tree has 2 files:

```
./src/readme
./src/readme.txt
```

./lakefile

``` Lua
target("install",{
  file.group{odir=path.join('.','dst'); src=path.join('.','src','readme.txt')};
  file.group{odir=path.join('.','dst'); src=path.join('.','src','readme')};
})

default("install")
```

`lake -v`

```
...
target: .\dst\readme*
.\dst\readme*   .\src\readme*   -1      -1
copy .\src\readme* .\dst\readme*
...
```

Command `copy .\src\readme* .\dst\readme*` work on windows but may be on *nix it is not correct.
Also I think this is bug in lake. 
`file.group{odir=path.join('.','dst'); src=path.join('.','src','readme')};` should copy only one file.

**Comment by stevedonovan** [comment]
Yes, you are right - there is a bug.  On Linux I get

```
cp ./src/readme*  ./dst/readme*
cp: target './dst/readme.txt' is not a directory
```

Which happens because Unix shells expand the '*' wildcard before executing.

Lake should _not_ pass a wildcard to this command!  Let me have a look!

**Comment by stevedonovan** [comment]
That should fix the problem - I was using `ext='*'` to flag that a rule should use _any_ extension, but that '*' got added. So, another if-statement...

**Comment by moteus** [comment]
Now it works. Thanks.
