### ISSUE TITLE
Specifying output filename on c.shared?

### ISSUE THREAD

**Issue by soccermitchy** [stevedonovan/Lake#40]
How do I specify the output filename on c.shared? I can't seem to find any way to do it...

**Comment by moteus** [comment]
It is the first element in table (https://github.com/moteus/lua-odbc/blob/master/lakefile#L29)

**Comment by stevedonovan** [comment]
Yes, you can say `c.shared {'mydll',src='myprog',...}`.  If there is no `src` then it becomes the same as the output name.

**Comment by soccermitchy** [comment]
Ah, I see.
