### ISSUE TITLE
error while include *.c file

### ISSUE THREAD

**Issue by moteus** [stevedonovan/Lake#5]
in my file i have : #include "some.c"
command line is:  cl  ... /showIncludes ...
produce output : Note: including file:     ....\some.c
in filter we match this line as file target 

function c.filter(line,action)
....
elseif line:match(file_pat) then
..
end

**Comment by stevedonovan** [comment]
You will have to give me more background - maybe give me a lakefile
and a very simple job that illustrates the problem.

The only problem with using c.filter with CL is that it overrides the
usual meaning, which is to collect the dependencies and generate a .d
file.

**Comment by stevedonovan** [comment]
Right, I can reproduce the problem - should be fixed by tomorrow!

**Comment by stevedonovan** [comment]
Right, the file_pat was falsely matching on the ..\file.c...

My fix is to define file_pat to try match a plain file name followed
by '.c' (or .cpp, etc)

file_pat = '^[^:]-%'..rule.in_ext..'$'

That is, ^[^:] instead of ., which matches _anything_ upto .c

steve d.
